CREATE TABLE `commodity_type` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '商品分类 ID',
  `typeName` varchar(255) NOT NULL COMMENT '商品类别名称',
  `createTime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `isDelete` tinyint(4) DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1900438197696618498 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
